---
- hosts: all

  roles:
  - role: geerlingguy.mysql
    become: yes

  tasks:

  - name: install gcc 
    package:
      name: gcc 
      state: present
    become: yes

  - name: install vim 
    package:
      name: vim 
      state: present
    become: yes

  - name: install screen
    package:
      name: screen
      state: present
    become: yes

  - name: bashrc
    copy:
      src: assets/.bashrc 
      dest: ~/.bashrc

  - name: screenrc
    copy:
      src: assets/.screenrc
      dest: ~/.screenrc
