---
- hosts: all

  roles:
  - role: geerlingguy.mysql
    become: yes
  - role: manala.vim 
    become: yes

  tasks:

  - name: install screen
    package:
      name: screen
      state: present
    become: yes

  - name: bashrc
    copy:
      src: assets/.bashrc 
      dest: ~/.bashrc

  - name: screenrc
    copy:
      src: assets/.screenrc
      dest: ~/.screenrc
