---
- hosts: all

  tasks:

  - name: install screen
    package:
      name: screen
      state: present
    become: yes

  - name: bashrc
    copy:
      src: assets/.bashrc 
      dest: ~vagrant/.bashrc

  - name: screenrc
    copy:
      src: assets/.screenrc
      dest: ~vagrant/.screenrc

