---
- hosts: all

  tasks:

  - name: install screen
    package:
      name: screen
      state: present
    become: yes

  - name: bashrc
    copy:
      src: assets/.bashrc 
      dest: ~/.bashrc

  - name: screenrc
    copy:
      src: assets/.screenrc
      dest: ~/.screenrc

  - name: mysql installation
    roles:
     - { role: geerlingguy.mysql }
    become: yes
